# Basic Reasoning - Hierarchical Diagnostic RAG Configuration
# Uses foundation datasets exclusively from data/foundation/

data_dir: data/foundation

# Model configurations (M1 Mac optimized)
models:
  embedding:
    name: sentence-transformers/all-MiniLM-L6-v2
    device: mps  # M1 Mac GPU acceleration
    batch_size: 16
  llm:
    name: mistral:7b-instruct
    temperature: 0.7
    context_window: 4096

# Hierarchical retrieval with three tiers
hierarchical_retrieval:
  tier1_top_k: 5        # Pattern Recognition - fast initial screening
  tier2_top_k: 3        # Hypothesis Testing - reasoning chains
  tier3_top_k: 2        # Confirmation - clinical evidence
  enable_evidence_stratification: true
  enable_temporal_weighting: true

# Processing configurations
processing:
  chunk_size: 512
  chunk_overlap: 100

# Hierarchical prompts for three-tier reasoning
prompts:
  system: |
    You are a medical assistant that answers multiple choice questions.
    Based on evidence-based medicine and therapeutic benefits, select the BEST option.
    Respond with ONLY the letter choice (A, B, C, or D) - no explanations.
    Choose the option that provides the most therapeutic benefit to the patient.
    
  tier1_prompt: |
    Based on these therapeutic patterns, which option provides the best patient care?
    Answer with only the letter (A, B, C, or D).
    
  tier2_prompt: |
    Using these clinical guidelines, which option is most supported by evidence?
    Answer with only the letter (A, B, C, or D).
    
  tier3_prompt: |
    Based on all evidence, which option provides the best therapeutic outcome?
    Answer with only the letter (A, B, C, or D).
# Web interface
web:
  host: 0.0.0.0
  port: 8503  # Basic reasoning system port (different from simple:8501, kg:8502)
  cors_origins: ["*"]