# Basic Reasoning - Hierarchical Diagnostic RAG Configuration
# Uses foundation datasets exclusively from data/foundation/

data_dir: data/foundation

# Model configurations (M1 Mac optimized)
models:
  embedding:
    name: sentence-transformers/all-MiniLM-L6-v2
    device: mps  # M1 Mac GPU acceleration
    batch_size: 16
  llm:
    name: mistral:7b-instruct
    temperature: 0.7
    context_window: 4096

# Hierarchical retrieval with three tiers
hierarchical_retrieval:
  tier1_top_k: 5        # Pattern Recognition - fast initial screening
  tier2_top_k: 3        # Hypothesis Testing - reasoning chains
  tier3_top_k: 2        # Confirmation - clinical evidence
  enable_evidence_stratification: true
  enable_temporal_weighting: true

# Processing configurations
processing:
  chunk_size: 512
  chunk_overlap: 100

# Hierarchical prompts for medical multiple choice questions
prompts:
  system: |
    You are a medical knowledge assistant specialized in answering multiple choice questions.
    You must analyze the question using three-tier hierarchical reasoning and select the correct answer.
    
    CRITICAL INSTRUCTIONS:
    - Always answer with ONLY the letter (A, B, C, D, or E)
    - Format your final answer as: "Answer: [LETTER]"
    - Use the provided medical knowledge to reason through each option
    - Be precise and evidence-based in your analysis
    
    EXAMPLE FORMAT:
    Question: What is the most common cause of pneumonia?
    Options: A) Virus B) Bacteria C) Fungus D) Parasite
    
    Analysis: [brief reasoning]
    Answer: B
    
  tier1_prompt: |
    TIER 1 - PATTERN RECOGNITION: Identify key medical concepts, symptoms, anatomy, and basic classifications.
    Use these foundational patterns to understand what the question is asking about.
    Focus on: definitions, basic anatomy, fundamental medical concepts, symptom recognition.
    
  tier2_prompt: |
    TIER 2 - CLINICAL REASONING: Apply clinical knowledge, pathophysiology, and diagnostic criteria.
    Use these clinical insights to evaluate each answer option systematically.
    Focus on: disease mechanisms, clinical presentations, diagnostic criteria, treatment principles.
    
  tier3_prompt: |
    TIER 3 - EVIDENCE CONFIRMATION: Confirm with established medical facts, guidelines, and evidence.
    Use this authoritative knowledge to definitively select the correct answer.
    Focus on: medical guidelines, established facts, evidence-based medicine, definitive criteria.

# Web interface
web:
  host: 0.0.0.0
  port: 8503  # Basic reasoning system port (different from simple:8501, kg:8502)
  cors_origins: ["*"]