# Enhanced Basic Reasoning - Hierarchical Medical Q&A Configuration
# Optimized for MIRAGE benchmark and medical multiple choice questions
# Updated to use Microsoft BiomedNLP-PubMedBERT medical embedding

data_dir: data/foundation

# Model configurations with medical embeddings
models:
  embedding:
    name: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext  # Primary medical embedding
    fallback_name: sentence-transformers/all-MiniLM-L6-v2  # Fallback if medical model fails
    device: mps  # M1 Mac GPU acceleration (change to cuda for NVIDIA GPUs)
    batch_size: 8   # Reduced for larger medical model
    max_length: 512
    normalize_embeddings: true
    trust_remote_code: false
    use_medical_embedding: true
    
    # Performance optimizations for medical model
    model_kwargs:
      torch_dtype: float16  # Use half precision for memory efficiency
      attn_implementation: "eager"  # More stable for medical models
    
    # Device-specific overrides
    device_settings:
      cuda:
        batch_size: 16
        mixed_precision: true
      mps:
        batch_size: 8
        mixed_precision: false
      cpu:
        batch_size: 4
        mixed_precision: false

  llm:
    name: mistral:7b-instruct
    temperature: 0.1  # Lower for more consistent answers
    context_window: 4096
    device: auto  # Auto-detect device

# Enhanced hierarchical retrieval with medical optimization
hierarchical_retrieval:
  tier1_top_k: 5        # Pattern Recognition - basic medical concepts
  tier2_top_k: 4        # Clinical Reasoning - increased for better coverage
  tier3_top_k: 3        # Evidence Confirmation - more evidence
  enable_evidence_stratification: true
  enable_temporal_weighting: true
  medical_specialty_boost: true  # Boost specialty-matched content
  balanced_tier_distribution: true  # Force balanced distribution
  
  # Medical-specific retrieval parameters
  medical_entity_boost: 1.3  # Boost documents with medical entities
  clinical_context_window: 3  # Consider surrounding context for clinical relevance

# Processing configurations optimized for medical content
processing:
  chunk_size: 384  # Reduced for medical model context
  chunk_overlap: 96  # 25% overlap
  min_content_length: 50  # Ensure meaningful medical content
  enable_medical_entity_recognition: true
  preserve_medical_terminology: true  # Don't split medical terms
  
  target_tier_distribution:  # Target balanced distribution
    tier1: 0.30  # 30% Pattern Recognition
    tier2: 0.40  # 40% Clinical Reasoning  
    tier3: 0.30  # 30% Evidence Confirmation

# Enhanced prompts specifically designed for medical multiple choice questions
prompts:
  system: |
    You are a medical knowledge expert designed to answer medical multiple-choice questions with accuracy and precision.
    
    YOUR ROLE:
    - Analyze medical questions using established medical knowledge
    - Evaluate all provided options systematically  
    - Select the most accurate answer based on medical evidence
    - Provide clear, knowledge-based reasoning
    
    CRITICAL INSTRUCTIONS:
    - Always choose ONE of the provided options (A, B, C, D, or E)
    - Base your answer on established medical facts and guidelines
    - End your response with "Answer: [LETTER]" 
    - Focus on medical knowledge assessment, not treatment recommendations
    
    RESPONSE FORMAT:
    1. Brief analysis of the medical scenario
    2. Evaluation of the key options
    3. Selection based on medical evidence
    4. "Answer: [LETTER]"

  tier1_pattern_recognition: |
    You are analyzing basic medical concepts and foundational knowledge.
    
    Focus on:
    - Medical definitions and terminology
    - Basic anatomy and physiology 
    - Fundamental medical principles
    - Drug mechanisms and classifications
    - Pattern recognition in medical scenarios
    
    Provide clear, factual answers based on basic medical knowledge.
    Always end with "Answer: [LETTER]"

  tier2_clinical_reasoning: |
    You are applying clinical reasoning and diagnostic thinking.
    
    Focus on:
    - Clinical presentation analysis
    - Differential diagnosis considerations
    - Pathophysiology and disease mechanisms
    - Clinical decision-making processes
    - Patient care scenarios
    
    Use systematic clinical reasoning to evaluate options.
    Always end with "Answer: [LETTER]"

  tier3_evidence_confirmation: |
    You are referencing evidence-based medicine and clinical guidelines.
    
    Focus on:
    - Research findings and clinical studies
    - Established clinical guidelines and protocols
    - Evidence-based treatment recommendations
    - Outcome data and prognostic factors
    - Best practice confirmations
    
    Base your answer on the strongest available evidence.
    Always end with "Answer: [LETTER]"

generation:
  # Ensure consistent answer format
  enforce_answer_format: true
  answer_patterns:
    - "Answer: A"
    - "Answer: B" 
    - "Answer: C"
    - "Answer: D"
    - "Answer: E"
  
  # Temperature settings for medical accuracy
  temperature: 0.1  # Very low for consistent medical answers
  max_tokens: 300   # Shorter responses for efficiency
  
  # Stop sequences to ensure proper format
  stop_sequences:
    - "Question:"
    - "Next question"
    - "\n\nQuestion"

# Evaluation and validation settings
evaluation:
  enable_medical_validation: true
  check_medical_terminology: true
  validate_clinical_accuracy: true