# Enhanced Basic Reasoning - Hierarchical Medical Q&A Configuration
# Optimized for MIRAGE benchmark and medical multiple choice questions

data_dir: data/foundation

# Model configurations with medical embeddings
models:
  embedding:
    name: sentence-transformers/all-MiniLM-L6-v2  # Will be overridden with medical embedding
    medical_embedding: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext  # Medical-specific embedding
    device: mps  # M1 Mac GPU acceleration
    batch_size: 16
    use_medical_embedding: true
  llm:
    name: mistral:7b-instruct
    temperature: 0.3  # Lower for more consistent answers
    context_window: 4096

# Enhanced hierarchical retrieval with medical optimization
hierarchical_retrieval:
  tier1_top_k: 5        # Pattern Recognition - basic medical concepts
  tier2_top_k: 4        # Clinical Reasoning - increased for better coverage
  tier3_top_k: 3        # Evidence Confirmation - more evidence
  enable_evidence_stratification: true
  enable_temporal_weighting: true
  medical_specialty_boost: true  # Boost specialty-matched content
  balanced_tier_distribution: true  # Force balanced distribution

# Processing configurations optimized for medical content
processing:
  chunk_size: 512
  chunk_overlap: 100
  min_content_length: 50  # Ensure meaningful medical content
  enable_medical_entity_recognition: true
  target_tier_distribution:  # Target balanced distribution
    tier1: 0.30  # 30% Pattern Recognition
    tier2: 0.40  # 40% Clinical Reasoning  
    tier3: 0.30  # 30% Evidence Confirmation

# Enhanced prompts specifically designed for medical multiple choice questions
prompts:
  system: |
    You are a medical knowledge expert answering multiple choice questions.
    Analyze each question systematically using hierarchical medical reasoning.
    
    CRITICAL REQUIREMENTS:
    - Select ONLY ONE answer: A, B, C, D, or E
    - Format your final answer as: "Answer: [LETTER]"
    - Base your answer on medical evidence and established knowledge
    - Be precise, accurate, and evidence-based
    
    RESPONSE FORMAT:
    1. Brief analysis of the question topic
    2. Systematic evaluation of key options
    3. Selection of the best answer
    4. Final answer: "Answer: [LETTER]"
    
    EXAMPLE:
    Question: What is the most common cause of community-acquired pneumonia?
    Options: A) Mycoplasma B) Streptococcus pneumoniae C) Haemophilus influenzae D) Staphylococcus aureus
    
    Analysis: Community-acquired pneumonia etiology varies by population and setting. S. pneumoniae remains the leading bacterial cause in most populations, particularly in adults without comorbidities.
    
    Answer: B
    
  tier1_prompt: |
    TIER 1 - MEDICAL PATTERN RECOGNITION:
    Analyze the basic medical concepts, definitions, anatomy, and fundamental knowledge patterns.
    
    Focus areas:
    • Medical terminology and definitions
    • Basic anatomy and physiology
    • Fundamental disease concepts
    • Clinical presentations and symptoms
    • Basic classifications and categories
    
    Use this foundational knowledge to understand what the question is asking about.
    
  tier2_prompt: |
    TIER 2 - CLINICAL REASONING:
    Apply clinical knowledge, pathophysiology, and diagnostic reasoning.
    
    Focus areas:
    • Disease mechanisms and pathophysiology
    • Clinical decision-making processes
    • Diagnostic criteria and differential diagnosis
    • Treatment principles and management approaches
    • Risk factors and prognostic indicators
    
    Use this clinical knowledge to systematically evaluate each answer option.
    
  tier3_prompt: |
    TIER 3 - EVIDENCE-BASED CONFIRMATION:
    Confirm with established medical facts, guidelines, and research evidence.
    
    Focus areas:
    • Clinical practice guidelines (WHO, AHA, ESC, etc.)
    • Evidence-based medicine and research findings
    • Established medical standards and protocols
    • Authoritative medical recommendations
    • Definitive diagnostic and treatment criteria
    
    Use this authoritative knowledge to select the most accurate answer.

# Web interface
web:
  host: 0.0.0.0
  port: 8503
  cors_origins: ["*"]

# Enhanced evaluation settings
evaluation:
  enable_answer_extraction: true
  answer_validation_strict: true
  require_final_answer_format: true
  log_reasoning_steps: true