# Basic Reasoning System GPU Configuration (RunPod/CUDA)
# Hierarchical Diagnostic RAG for GPU evaluation

# Environment
environment: "gpu"
platform: "runpod"

# Data directory
data_dir: data/foundation

# GPU-optimized model configurations
models:
  embedding:
    name: sentence-transformers/all-MiniLM-L6-v2
    device: cuda
    batch_size: 64  # Higher for GPU
    max_length: 512
    normalize_embeddings: true
    trust_remote_code: false
    # GPU optimizations
    mixed_precision: true
    compile_model: true
  
  llm:
    name: mistral:7b-instruct
    device: cuda
    temperature: 0.7
    context_window: 4096
    max_new_tokens: 512
    # GPU optimizations
    batch_size: 32
    mixed_precision: true
    use_flash_attention: true

# GPU-optimized hierarchical retrieval with three tiers
hierarchical_retrieval:
  tier1_top_k: 8        # Pattern Recognition - more results on GPU
  tier2_top_k: 5        # Hypothesis Testing - reasoning chains
  tier3_top_k: 3        # Confirmation - clinical evidence
  enable_evidence_stratification: true
  enable_temporal_weighting: true
  # GPU-specific settings
  batch_size: 64
  parallel_processing: true
  num_workers: 4
  pin_memory: true

# GPU-optimized processing
processing:
  chunk_size: 512
  chunk_overlap: 100
  # GPU batch processing
  batch_size: 128
  num_workers: 4
  pin_memory: true

# Hierarchical prompts for medical multiple choice questions (GPU optimized)
prompts:
  system: |
    You are a medical knowledge assistant specialized in answering multiple choice questions.
    You must analyze the question using three-tier hierarchical reasoning and select the correct answer.
    
    CRITICAL INSTRUCTIONS:
    - Always answer with ONLY the letter (A, B, C, D, or E)
    - Format your final answer as: "Answer: [LETTER]"
    - Use the provided medical knowledge to reason through each option
    - Be precise and evidence-based in your analysis
    - Keep responses concise for GPU efficiency
    
    EXAMPLE FORMAT:
    Question: What is the most common cause of pneumonia?
    Options: A) Virus B) Bacteria C) Fungus D) Parasite
    
    Analysis: [brief reasoning]
    Answer: B
    
  tier1_prompt: |
    TIER 1 - PATTERN RECOGNITION: Identify key medical concepts, symptoms, anatomy, and basic classifications.
    Use these foundational patterns to understand what the question is asking about.
    Focus on: definitions, basic anatomy, fundamental medical concepts, symptom recognition.
    
  tier2_prompt: |
    TIER 2 - CLINICAL REASONING: Apply clinical knowledge, pathophysiology, and diagnostic criteria.
    Use these clinical insights to evaluate each answer option systematically.
    Focus on: disease mechanisms, clinical presentations, diagnostic criteria, treatment principles.
    
  tier3_prompt: |
    TIER 3 - EVIDENCE CONFIRMATION: Confirm with established medical facts, guidelines, and evidence.
    Use this authoritative knowledge to definitively select the correct answer.
    Focus on: medical guidelines, established facts, evidence-based medicine, definitive criteria.