# Basic Reasoning - Hierarchical Diagnostic RAG Configuration
# Uses foundation datasets exclusively from data/foundation/

data_dir: data/foundation

# Model configurations (M1 Mac optimized)
models:
  embedding:
    name: sentence-transformers/all-MiniLM-L6-v2
    device: mps  # M1 Mac GPU acceleration
    batch_size: 16
  llm:
    name: mistral:7b-instruct
    temperature: 0.7
    context_window: 4096

# Hierarchical retrieval with three tiers
hierarchical_retrieval:
  tier1_top_k: 5        # Pattern Recognition - fast initial screening
  tier2_top_k: 3        # Hypothesis Testing - reasoning chains
  tier3_top_k: 2        # Confirmation - clinical evidence
  enable_evidence_stratification: true
  enable_temporal_weighting: true

# Processing configurations
processing:
  chunk_size: 512
  chunk_overlap: 100

# Hierarchical prompts for three-tier reasoning
prompts:
  system: |
    You are a therapeutic guidance assistant that provides evidence-based treatment recommendations.
    Focus on proven clinical benefits, therapeutic advantages, and positive patient outcomes.
    Emphasize what treatments help patients rather than contraindications or dangers.
    Use three-tier reasoning: Pattern Recognition → Evidence-Based Guidelines → Treatment Confirmation.
    
  tier1_prompt: |
    Based on these therapeutic patterns, identify proven treatments and their clinical benefits.
    Focus on evidence-based therapies and positive outcomes documented in guidelines.
    
  tier2_prompt: |
    Using these clinical guidelines, explain the therapeutic benefits and evidence supporting recommended treatments.
    Emphasize how treatments improve patient outcomes and reduce disease complications.
    
  tier3_prompt: |
    Confirm treatment recommendations with comprehensive evidence of clinical benefits.
    Integrate all evidence to highlight therapeutic advantages and positive patient outcomes.

# Web interface
web:
  host: 0.0.0.0
  port: 8503  # Basic reasoning system port (different from simple:8501, kg:8502)
  cors_origins: ["*"]