# Enhanced Basic Reasoning - Hierarchical Medical Q&A Configuration
# Optimized for MIRAGE benchmark and medical multiple choice questions
# Updated to use Microsoft BiomedNLP-PubMedBERT medical embedding

data_dir: data/foundation

# Model configurations with medical embeddings
models:
  embedding:
    name: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext  # Primary medical embedding
    fallback_name: sentence-transformers/all-MiniLM-L6-v2  # Fallback if medical model fails
    device: mps  # M1 Mac GPU acceleration (change to cuda for NVIDIA GPUs)
    batch_size: 8   # Reduced for larger medical model
    max_length: 512
    normalize_embeddings: true
    trust_remote_code: false
    use_medical_embedding: true
    
    # Performance optimizations for medical model
    model_kwargs:
      torch_dtype: float16  # Use half precision for memory efficiency
      attn_implementation: "eager"  # More stable for medical models
    
    # Device-specific overrides
    device_settings:
      cuda:
        batch_size: 16
        mixed_precision: true
      mps:
        batch_size: 8
        mixed_precision: false
      cpu:
        batch_size: 4
        mixed_precision: false

  llm:
    name: mistral:7b-instruct
    temperature: 0.1  # Lower for more consistent answers
    context_window: 4096
    device: auto  # Auto-detect device

# Enhanced hierarchical retrieval with medical optimization
hierarchical_retrieval:
  tier1_top_k: 5        # Pattern Recognition - basic medical concepts
  tier2_top_k: 4        # Clinical Reasoning - increased for better coverage
  tier3_top_k: 3        # Evidence Confirmation - more evidence
  enable_evidence_stratification: true
  enable_temporal_weighting: true
  medical_specialty_boost: true  # Boost specialty-matched content
  balanced_tier_distribution: true  # Force balanced distribution
  
  # Medical-specific retrieval parameters
  medical_entity_boost: 1.3  # Boost documents with medical entities
  clinical_context_window: 3  # Consider surrounding context for clinical relevance

# Processing configurations optimized for medical content
processing:
  chunk_size: 384  # Reduced for medical model context
  chunk_overlap: 96  # 25% overlap
  min_content_length: 50  # Ensure meaningful medical content
  enable_medical_entity_recognition: true
  preserve_medical_terminology: true  # Don't split medical terms
  
  target_tier_distribution:  # Target balanced distribution
    tier1: 0.30  # 30% Pattern Recognition
    tier2: 0.40  # 40% Clinical Reasoning  
    tier3: 0.30  # 30% Evidence Confirmation

# Enhanced prompts specifically designed for medical multiple choice questions
prompts:
  system: |
    You are a medical knowledge expert answering multiple choice questions.
    Analyze each question systematically using medical knowledge and evidence.
    
    CRITICAL REQUIREMENTS:
    - You MUST select exactly ONE answer from the given options (A, B, C, D, or E)
    - Format your final answer EXACTLY as: "Answer: [LETTER]"
    - Base your analysis on established medical knowledge
    - Be precise, accurate, and evidence-based
    
    RESPONSE FORMAT:
    1. Identify the medical condition/scenario
    2. Determine the most likely treatment/intervention
    3. Analyze how this affects the specific physiological mechanism asked
    4. Evaluate each option systematically
    5. Select the correct answer
    6. End with: "Answer: [LETTER]"
    
    EXAMPLE:
    Question: A patient with anaphylaxis receives epinephrine. What effect does epinephrine have on cardiac pacemaker cells?
    Options: A) Increased Ca2+ influx B) Decreased Na+ influx C) No effect D) Increased K+ efflux
    
    Analysis: Anaphylaxis requires epinephrine as first-line treatment. Epinephrine is a beta-adrenergic agonist that increases cardiac chronotropy by enhancing calcium influx during phase 4 of pacemaker cell action potentials, leading to faster heart rate.
    
    Answer: A
    
  tier1_prompt: |
    TIER 1 - MEDICAL FOUNDATION:
    Focus on basic medical concepts, anatomy, physiology, and fundamental mechanisms.
    Identify core medical knowledge relevant to the question.
    
  tier2_prompt: |
    TIER 2 - CLINICAL APPLICATION:
    Apply clinical reasoning and diagnostic thinking.
    Consider pathophysiology, treatment protocols, and clinical presentations.
    
  tier3_prompt: |
    TIER 3 - EVIDENCE-BASED MEDICINE:
    Reference clinical guidelines, research evidence, and established protocols.
    Validate answers against current medical standards.

# Evaluation and validation settings
evaluation:
  enable_medical_validation: true
  check_medical_terminology: true
  validate_clinical_accuracy: true