# Enhanced Basic Reasoning - Hierarchical Medical Q&A Configuration
# Optimized for MIRAGE benchmark and medical multiple choice questions
# Updated to use Microsoft BiomedNLP-PubMedBERT medical embedding

data_dir: data/foundation

# Model configurations with medical embeddings
models:
  embedding:
    name: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext  # Primary medical embedding
    fallback_name: sentence-transformers/all-MiniLM-L6-v2  # Fallback if medical model fails
    device: mps  # M1 Mac GPU acceleration (change to cuda for NVIDIA GPUs)
    batch_size: 8   # Reduced for larger medical model
    max_length: 512
    normalize_embeddings: true
    trust_remote_code: false
    use_medical_embedding: true
    
    # Performance optimizations for medical model
    model_kwargs:
      torch_dtype: float16  # Use half precision for memory efficiency
      attn_implementation: "eager"  # More stable for medical models
    
    # Device-specific overrides
    device_settings:
      cuda:
        batch_size: 16
        mixed_precision: true
      mps:
        batch_size: 8
        mixed_precision: false
      cpu:
        batch_size: 4
        mixed_precision: false

  llm:
    name: mistral:7b-instruct
    temperature: 0.3  # Lower for more consistent answers
    context_window: 4096
    device: auto  # Auto-detect device

# Enhanced hierarchical retrieval with medical optimization
hierarchical_retrieval:
  tier1_top_k: 5        # Pattern Recognition - basic medical concepts
  tier2_top_k: 4        # Clinical Reasoning - increased for better coverage
  tier3_top_k: 3        # Evidence Confirmation - more evidence
  enable_evidence_stratification: true
  enable_temporal_weighting: true
  medical_specialty_boost: true  # Boost specialty-matched content
  balanced_tier_distribution: true  # Force balanced distribution
  
  # Medical-specific retrieval parameters
  medical_entity_boost: 1.2  # Boost documents with medical entities
  clinical_context_window: 3  # Consider surrounding context for clinical relevance

# Processing configurations optimized for medical content
processing:
  chunk_size: 384  # Reduced for medical model context
  chunk_overlap: 96  # 25% overlap
  min_content_length: 50  # Ensure meaningful medical content
  enable_medical_entity_recognition: true
  preserve_medical_terminology: true  # Don't split medical terms
  
  target_tier_distribution:  # Target balanced distribution
    tier1: 0.30  # 30% Pattern Recognition
    tier2: 0.40  # 40% Clinical Reasoning  
    tier3: 0.30  # 30% Evidence Confirmation

# Enhanced prompts specifically designed for medical multiple choice questions
prompts:
  system: |
    You are a medical knowledge expert answering multiple choice questions.
    Analyze each question systematically using hierarchical medical reasoning.
    
    CRITICAL REQUIREMENTS:
    - Select ONLY ONE answer: A, B, C, D, or E
    - Format your final answer as: "Answer: [LETTER]"
    - Base your answer on medical evidence and established knowledge
    - Be precise, accurate, and evidence-based
    
    RESPONSE FORMAT:
    1. Brief analysis of the question topic
    2. Systematic evaluation of key options
    3. Selection of the best answer
    4. Final answer: "Answer: [LETTER]"
    
    EXAMPLE:
    Question: What is the most common cause of community-acquired pneumonia?
    Options: A) Mycoplasma B) Streptococcus pneumoniae C) Haemophilus influenzae D) Staphylococcus aureus
    
    Analysis: Community-acquired pneumonia etiology varies by population and setting. S. pneumoniae remains the leading bacterial cause in most populations, particularly in adults without comorbidities.
    
    Answer: B
    
  tier1_prompt: |
    TIER 1 - MEDICAL PATTERN RECOGNITION:
    Analyze the basic medical concepts, definitions, anatomy, and fundamental knowledge patterns.
    Focus on established medical facts, terminology, and basic pathophysiology.
    
  tier2_prompt: |
    TIER 2 - CLINICAL REASONING:
    Apply clinical reasoning and diagnostic thinking to the medical scenario.
    Consider differential diagnosis, clinical presentations, and diagnostic approaches.
    
  tier3_prompt: |
    TIER 3 - EVIDENCE CONFIRMATION:
    Evaluate evidence-based medicine, treatment guidelines, and research findings.
    Consider latest clinical guidelines, treatment protocols, and research evidence.

# Evaluation and validation settings
evaluation:
  enable_medical_validation: true
  check_medical_terminology: true
  validate_clinical_accuracy: true