# Enhanced Basic Reasoning - GPU Configuration
# Optimized for CUDA/RunPod environments with Microsoft BiomedNLP-PubMedBERT

data_dir: data/foundation

# Model configurations optimized for GPU with medical embeddings
models:
  embedding:
    name: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
    fallback_name: sentence-transformers/all-MiniLM-L6-v2
    device: cuda
    batch_size: 32  # Higher batch size for GPU
    max_length: 512
    normalize_embeddings: true
    trust_remote_code: false
    use_medical_embedding: true
    
    # GPU optimizations
    model_kwargs:
      torch_dtype: float16
      attn_implementation: "flash_attention_2"  # Use flash attention if available
    
    # GPU performance settings
    compile_model: true
    mixed_precision: true
    gradient_checkpointing: false  # Disable for inference
    memory_efficient: true

  llm:
    name: mistral:7b-instruct
    temperature: 0.2  # Lower for GPU consistency
    context_window: 4096
    device: cuda
    
    # GPU optimizations
    batch_size: 16
    mixed_precision: true
    use_flash_attention: true

# Enhanced hierarchical retrieval for GPU
hierarchical_retrieval:
  tier1_top_k: 8        # Increased for GPU processing power
  tier2_top_k: 6        # More documents for better coverage
  tier3_top_k: 4        # More evidence retrieval
  enable_evidence_stratification: true
  enable_temporal_weighting: true
  medical_specialty_boost: true
  balanced_tier_distribution: true
  
  # GPU-specific optimizations
  batch_retrieval: true
  parallel_tier_processing: true
  gpu_accelerated_search: true

# Processing optimized for GPU memory
processing:
  chunk_size: 384
  chunk_overlap: 96
  min_content_length: 50
  enable_medical_entity_recognition: true
  preserve_medical_terminology: true
  
  # GPU batch processing
  batch_size: 64
  num_workers: 4
  pin_memory: true
  
  target_tier_distribution:
    tier1: 0.30
    tier2: 0.40
    tier3: 0.30

# Performance settings for GPU
performance:
  use_gpu_acceleration: true
  mixed_precision: true
  compile_models: true
  memory_efficient: true
  
  # CUDA optimizations
  cuda_deterministic: false
  cuda_benchmark: true
  
  # Memory management for GPU
  gpu_memory_fraction: 0.8
  memory_growth: true
  max_memory_per_process: "20GB"

# Enhanced prompts (same as base config)
prompts:
  system: |
    You are a medical knowledge expert answering multiple choice questions.
    Analyze each question systematically using hierarchical medical reasoning.
    
    CRITICAL REQUIREMENTS:
    - Select ONLY ONE answer: A, B, C, D, or E
    - Format your final answer as: "Answer: [LETTER]"
    - Base your answer on medical evidence and established knowledge
    - Be precise, accurate, and evidence-based
    
    RESPONSE FORMAT:
    1. Brief analysis of the question topic
    2. Systematic evaluation of key options
    3. Selection of the best answer
    4. Final answer: "Answer: [LETTER]"
    
  tier1_prompt: |
    TIER 1 - MEDICAL PATTERN RECOGNITION:
    Analyze the basic medical concepts, definitions, anatomy, and fundamental knowledge patterns.
    Focus on established medical facts, terminology, and basic pathophysiology.
    
  tier2_prompt: |
    TIER 2 - CLINICAL REASONING:
    Apply clinical reasoning and diagnostic thinking to the medical scenario.
    Consider differential diagnosis, clinical presentations, and diagnostic approaches.
    
  tier3_prompt: |
    TIER 3 - EVIDENCE CONFIRMATION:
    Evaluate evidence-based medicine, treatment guidelines, and research findings.
    Consider latest clinical guidelines, treatment protocols, and research evidence.