# HierRAGMed Evaluation Configuration - Updated for Medical Embeddings
# Universal configuration adapted for Microsoft BiomedNLP-PubMedBERT

# Platform identification
platform: "Generic"
environment: "development"
gpu_optimized: false

# Directory structure
results_dir: "evaluation/results"
data_dir: "data"
cache_dir: "evaluation/cache"
logs_dir: "evaluation/logs"

# Enhanced model configurations with medical embedding
models:
  embedding:
    name: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
    fallback_name: "sentence-transformers/all-MiniLM-L6-v2"
    device: "auto"  # Auto-detect: cuda > mps > cpu
    batch_size: 16   # Conservative default (adaptive)
    max_length: 512
    normalize_embeddings: true
    trust_remote_code: false
    use_medical_embedding: true
    
    # Model loading optimizations
    model_kwargs:
      torch_dtype: "float16"  # Will be adjusted per device
      attn_implementation: "eager"
    
    # Device-specific overrides for medical model
    device_settings:
      cuda:
        batch_size: 32
        mixed_precision: true
        model_kwargs:
          torch_dtype: "float16"
          attn_implementation: "flash_attention_2"
      mps:
        batch_size: 8
        mixed_precision: false
        model_kwargs:
          torch_dtype: "float16"
          attn_implementation: "eager"
      cpu:
        batch_size: 4
        mixed_precision: false
        model_kwargs:
          torch_dtype: "float32"
          attn_implementation: "eager"
    
  llm:
    name: "mistral:7b-instruct"
    device: "auto"  # Auto-detect: cuda > mps > cpu
    batch_size: 16   # Conservative default
    temperature: 0.7
    context_window: 4096
    max_new_tokens: 512
    do_sample: false
    
    # Device-specific overrides
    device_settings:
      cuda:
        batch_size: 32
        mixed_precision: true
      mps:
        batch_size: 8
        mixed_precision: false
      cpu:
        batch_size: 4
        mixed_precision: false
  
  # Model system configurations
  kg_system:
    enabled: true
    device: "auto"
    memory_efficient: true
    compile_model: false  # Conservative default
    mixed_precision: false  # Conservative default
    gradient_checkpointing: false
    
    # KG-specific embedding config
    embedding:
      name: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
      use_medical_embedding: true
    
  hierarchical_system:
    enabled: true
    device: "auto"
    memory_efficient: true
    compile_model: false
    mixed_precision: false
    gradient_checkpointing: false
    
    # Hierarchical-specific embedding config
    embedding:
      name: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
      use_medical_embedding: true

# Performance configuration (adaptive)
performance:
  # Auto-detection settings
  auto_detect_device: true
  auto_optimize_batch_size: true
  auto_tune_memory: true
  
  # Conservative defaults
  use_gpu_acceleration: false  # Will be enabled if GPU detected
  mixed_precision: false
  compile_models: false
  memory_efficient: true
  
  # Medical model specific optimizations
  medical_model_optimizations:
    enable_gradient_checkpointing: false  # For inference
    use_attention_optimization: true
    enable_model_parallelism: false

# Evaluation specific settings
evaluation:
  # Medical embedding optimizations
  enable_medical_validation: true
  check_medical_terminology: true
  validate_clinical_accuracy: true
  
  # Similarity computation for medical content
  similarity_model: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
  fallback_similarity_model: "sentence-transformers/all-MiniLM-L6-v2"
  
  # Evaluation parameters
  batch_size: 8  # Conservative for medical model
  max_workers: 2
  timeout_per_question: 120  # Increased for medical processing

# Benchmark configurations
benchmarks:
  mirage:
    enabled: true
    medical_focus: true
    use_medical_embedding: true
  
  med_qa:
    enabled: true
    medical_focus: true
    use_medical_embedding: true
  
  pub_med_qa:
    enabled: true
    medical_focus: true
    use_medical_embedding: true

# Logging configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | MedEval | {message}"
  rotation: "1 day"
  retention: "7 days"
  
  # Medical evaluation specific logging
  log_medical_validation: true
  log_embedding_performance: true
  log_device_utilization: true